apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-frontend-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-frontend-flask
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: app-frontend-flask
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: container-frontend-flask
        image: peterdevopscr.azurecr.io/uwsgi-nginx-flask:python3.6
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: service-frontend-flask
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: app-frontend-flask
