apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-backend-powershell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-backend-powershell
  template:
    metadata:
      labels:
        app: app-backend-powershell
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: container-backend-powershell
        image: mcr.microsoft.com/powershell:latest
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 8888
          name: powershell
---
apiVersion: v1
kind: Service
metadata:
  name: service-backend-powershell
spec:
  ports:
  - port: 6379
  selector:
    app: app-backend-powershell
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-frontend-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-frontend-flask
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: app-frontend-flask
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: container-frontend-flask
        image: mcr.microsoft.com/azuredocs/azure-vote-front:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: service-frontend-flask
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: app-frontend-flask
